apiVersion: v1
kind: Secret
metadata:
  name: healthsys-secrets
  namespace: healthsys
type: Opaque
stringData:
  postgres-password: "healthsys-prod-password"
  rabbitmq-password: "healthsys-rabbitmq-password"
  jwt-secret: "healthsys-prod-jwt-secret-min-32-chars-long"
  bootstrap-admin-password: "Admin@123"
