spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-auth
              uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
            - id: identity-users
              uri: ${IDENTITY_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/users/**
            - id: patient-service
              uri: ${PATIENT_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/patients/**
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - ${APP_CORS_ALLOWED_ORIGIN_DEV:http://localhost:5173}
                  - ${APP_CORS_ALLOWED_ORIGIN_DEV_ALT:http://127.0.0.1:5173}
                  - ${APP_CORS_ALLOWED_ORIGIN_DOCKER:http://localhost:4173}
                  - ${APP_CORS_ALLOWED_ORIGIN_DOCKER_ALT:http://127.0.0.1:4173}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${SERVER_PORT:8080}
